version: "3.3"
services:
  db:
    image: "postgres:14.2"
    restart:
      unless-stopped
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "go_demo"
      POSTGRES_URL: "postgres://postgres:postgres@localhost:5430/go_demo?sslmode=verify-full" # หรือ sslmode=verify-full